language: haskell
install:
  - cd tests
  - cabal install elm-make
  - cabal install elm-package
  - curl https://raw.githubusercontent.com/maxsnew/IO/master/elm-io.sh > elm-io.sh
  - npm install jsdom
  - npm install elm-test
  - elm-package install -y
script: elm-test ConsoleRunner.elm
